services:
  backend:
    build: .
    ports:
      - "3333:3333"
    environment:
      - APP_PORT=3333
      - JWT_SECRET=batman_secret
      - DB_HOST=db
      - DB_USER=docker
      - DB_PASSWORD=123
      - DB_NAME=snet_db
      - DB_PORT=5432
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=redis
    depends_on:
      - db
      - redis
    command: |
      sh -c "until nc -z db 5432; do echo 'waiting db...'; sleep 1; done && ./backend"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: snet_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
