name: ci

on: [push]

jobs:
  checkout-code:
    runs-on: ubuntu-latest

    steps:
    # Faz checkout do repositório inteiro
    - name: Checkout repository
      uses: actions/checkout@v3

    # ----------- BACKEND -----------
    - name: Handle backend
      run: |
        [ -d "./backend" ] && echo "Backend folder found."
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22
    
    - name: Build backend
      working-directory: "./backend"
      run: go build -o api ./cmd/api

    # ----------- FRONTEND -----------
    - name: Handle frontend
      run: |
        [ -d "./frontend" ] && echo "Frontend folder found."

    - name: Install frontend dependencies
      working-directory: "./frontend"
      run: npm ci

    - name: Build frontend
      working-directory: "./frontend"
      run: npm run build
