name: Multi-Project Checkout
on: [push]

jobs:
  checkout-code:
    runs-on: ubuntu-latest

    steps:
    # Faz checkout do repositório inteiro
    - name: Checkout repository
      uses: actions/checkout@v3

    # Lida com o backend
    - name: Handle backend
      run: |
        [ -d "./backend" ] && echo "Backend folder found."

    - name: Handle frontend
      run: |
        [ -d "./frontend" ] && echo "Frontend folder found."
