name: Multi-Project Checkout
on: [push]

jobs:
  checkout-code:
    runs-on: ubuntu-latest

    steps:
    # Faz checkout do repositório inteiro
    - name: Checkout repository
      uses: actions/checkout@v3

    # Lida com o backend
    - name: Handle backend
      run: |
        if [ -d "./backend" ]; then
          echo "Backend folder found."
        fi

    # Lida com o frontend
    - name: Handle frontend
      run: |
        if [ -d "./frontend" ]; then
          echo "Frontend folder found."
        fi